version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    executor: android/android

    docker:
      - image: circleci/openjdk:17-jdk
      
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download and Install JDK 17
          command: |
            JDK_URL="https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz"
            JDK_DIR="$HOME/jdk-17"

            mkdir -p $JDK_DIR
            curl -L $JDK_URL -o jdk.tar.gz
            tar xzf jdk.tar.gz -C $JDK_DIR --strip-components=1
            rm jdk.tar.gz

            echo 'export PATH=$JDK_DIR/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

            java -version  # Memeriksa instalasi JDK

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
